// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticates a user and returns a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login data",
                        "name": "loginData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/profile": {
  "get": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Returns the authenticated user's profile",
    "produces": [
      "application/json"
    ],
    "tags": [
      "auth"
    ],
    "summary": "Get user profile",
    "responses": {
      "200": {
        "description": "OK",
        "schema": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "401": {
        "description": "Unauthorized",
        "schema": {
          "type": "object",
          "additionalProperties": true
        }
      }
    }
  },
  "put": {
    "consumes": [
      "application/json"
    ],
    "description": "Updates the authenticated user's profile information",
    "parameters": [
      {
        "description": "Profile update data",
        "in": "body",
        "name": "profileData",
        "required": true,
        "schema": {
          "type": "object",
          "additionalProperties": true
        }
      }
    ],
    "produces": [
      "application/json"
    ],
    "responses": {
      "200": {
        "description": "OK",
        "schema": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "400": {
        "description": "Bad Request",
        "schema": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "401": {
        "description": "Unauthorized",
        "schema": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "404": {
        "description": "Not Found",
        "schema": {
          "type": "object",
          "additionalProperties": true
        }
      }
    },
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "summary": "Update user profile",
    "tags": [
      "auth"
    ]
  }
},
"/api/v1/auth/change-password": {
    "post": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Changes the authenticated user's password after verifying current password",
      "consumes": [
        "application/json"
      ],
      "produces": [
        "application/json"
      ],
      "tags": [
        "auth"
      ],
      "summary": "Change user password",
      "parameters": [
        {
          "description": "Password change data",
          "in": "body",
          "name": "passwordData",
          "required": true,
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        }
      ],
      "responses": {
        "200": {
          "description": "OK",
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "400": {
          "description": "Bad Request",
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "401": {
          "description": "Unauthorized",
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "/api/v1/auth/forgot-password": {
    "post": {
      "description": "Sends a password reset token to the user's email",
      "consumes": [
        "application/json"
      ],
      "produces": [
        "application/json"
      ],
      "tags": [
        "auth"
      ],
      "summary": "Request password reset",
      "parameters": [
        {
          "description": "Password reset request data",
          "in": "body",
          "name": "resetData",
          "required": true,
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        }
      ],
      "responses": {
        "200": {
          "description": "OK",
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "400": {
          "description": "Bad Request",
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "404": {
          "description": "Not Found",
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "/api/v1/auth/reset-password": {
    "post": {
      "description": "Resets user password using a valid reset token",
      "consumes": [
        "application/json"
      ],
      "produces": [
        "application/json"
      ],
      "tags": [
        "auth"
      ],
      "summary": "Reset password with token",
      "parameters": [
        {
          "description": "Password reset data",
          "in": "body",
          "name": "resetData",
          "required": true,
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        }
      ],
      "responses": {
        "200": {
          "description": "OK",
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "400": {
          "description": "Bad Request",
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "401": {
          "description": "Unauthorized",
          "schema": {
            "type": "object",
            "additionalProperties": true
          }
        }
      }
    }
  },
  
        "/api/v1/auth/register": {
            "post": {
                "description": "Registers a new user and sends a verification email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration data",
                        "name": "userData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/verify-email": {
            "post": {
                "description": "Verifies a user's email using a code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify email",
                "parameters": [
                    {
                        "description": "Verification code",
                        "name": "verifyData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/secrets/{app}/{name}": {
            "put": {
                "summary": "Create or update a secret",
                "description": "Creates or updates a secret for an app and organization",
                "tags": ["secrets"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "app", "in": "path", "required": true, "type": "string", "description": "App name" },
                    { "name": "name", "in": "path", "required": true, "type": "string", "description": "Secret name" },
                    { "name": "body", "in": "body", "required": true, "schema": { "type": "object" }, "description": "Secret data" }
                ],
                "responses": {
                    "201": { "description": "Secret created successfully", "schema": { "type": "object" } },
                    "200": { "description": "Secret updated successfully", "schema": { "type": "object" } },
                    "400": { "description": "Invalid request", "schema": { "type": "object" } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object" } },
                    "403": { "description": "Forbidden", "schema": { "type": "object" } },
                    "500": { "description": "Server error", "schema": { "type": "object" } }
                }
            },
            "get": {
                "summary": "Get a secret",
                "description": "Retrieves and decrypts a secret for an app and organization",
                "tags": ["secrets"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "app", "in": "path", "required": true, "type": "string", "description": "App name" },
                    { "name": "name", "in": "path", "required": true, "type": "string", "description": "Secret name" }
                ],
                "responses": {
                    "200": { "description": "Decrypted secret", "schema": { "type": "object" } },
                    "400": { "description": "Invalid request", "schema": { "type": "object" } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object" } },
                    "403": { "description": "Forbidden", "schema": { "type": "object" } },
                    "404": { "description": "Secret not found", "schema": { "type": "object" } },
                    "500": { "description": "Server error", "schema": { "type": "object" } }
                }
            },
            "delete": {
                "summary": "Delete a secret",
                "description": "Deletes a secret for an app and organization",
                "tags": ["secrets"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "app", "in": "path", "required": true, "type": "string", "description": "App name" },
                    { "name": "name", "in": "path", "required": true, "type": "string", "description": "Secret name" }
                ],
                "responses": {
                    "200": { "description": "Secret deleted successfully", "schema": { "type": "object" } },
                    "400": { "description": "Invalid request", "schema": { "type": "object" } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object" } },
                    "404": { "description": "Secret not found", "schema": { "type": "object" } },
                    "500": { "description": "Server error", "schema": { "type": "object" } }
                }
            }
        },
        "/api/v1/secrets/{app}": {
            "get": {
                "summary": "List secrets for an app",
                "description": "Lists all secrets for an app (without decryption)",
                "tags": ["secrets"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "app", "in": "path", "required": true, "type": "string", "description": "App name" }
                ],
                "responses": {
                    "200": { "description": "List of secrets", "schema": { "type": "object" } },
                    "400": { "description": "Invalid request", "schema": { "type": "object" } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object" } },
                    "500": { "description": "Server error", "schema": { "type": "object" } }
                }
            },
            "put": {
                "summary": "Bulk create or update secrets for an app",
                "description": "Bulk creates or updates secrets for an app",
                "tags": ["secrets"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "app", "in": "path", "required": true, "type": "string", "description": "App name" },
                    { "name": "body", "in": "body", "required": true, "schema": { "type": "object" }, "description": "Bulk secrets payload" }
                ],
                "responses": {
                    "200": { "description": "Bulk upsert result", "schema": { "type": "object" } },
                    "400": { "description": "Invalid request", "schema": { "type": "object" } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object" } },
                    "403": { "description": "Forbidden", "schema": { "type": "object" } },
                    "500": { "description": "Server error", "schema": { "type": "object" } }
                }
            },
            "delete": {
                "summary": "Bulk delete all secrets for an app",
                "description": "Bulk deletes all secrets for an app the user can manage",
                "tags": ["secrets"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "app", "in": "path", "required": true, "type": "string", "description": "App name" }
                ],
                "responses": {
                    "200": { "description": "Bulk delete result", "schema": { "type": "object" } },
                    "400": { "description": "Invalid request", "schema": { "type": "object" } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object" } },
                    "500": { "description": "Server error", "schema": { "type": "object" } }
                }
            }
        },
        "/api/v1/secrets/{app}/values": {
            "get": {
                "summary": "List secrets for an app with values",
                "description": "Lists all secrets for an app with decrypted values",
                "tags": ["secrets"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "app", "in": "path", "required": true, "type": "string", "description": "App name" }
                ],
                "responses": {
                    "200": { "description": "List of secrets with values", "schema": { "type": "object" } },
                    "400": { "description": "Invalid request", "schema": { "type": "object" } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object" } },
                    "500": { "description": "Server error", "schema": { "type": "object" } }
                }
            }
        },
        "/api/v1/secrets/user/all": {
            "get": {
                "summary": "List all secrets for a user",
                "description": "Lists all secrets for a user (personal + organization secrets they have access to)",
                "tags": ["secrets"],
                "produces": ["application/json"],
                "responses": {
                    "200": { "description": "List of secrets", "schema": { "type": "object" } },
                    "400": { "description": "Invalid request", "schema": { "type": "object" } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object" } },
                    "500": { "description": "Server error", "schema": { "type": "object" } }
                }
            }
        },
        "/api/v1/secrets/organization/{orgId}": {
            "get": {
                "summary": "List all secrets for an organization",
                "description": "Lists all secrets for an organization (only for admin/owner)",
                "tags": ["secrets"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "orgId", "in": "path", "required": true, "type": "string", "description": "Organization ID" }
                ],
                "responses": {
                    "200": { "description": "List of secrets", "schema": { "type": "object" } },
                    "400": { "description": "Invalid request", "schema": { "type": "object" } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object" } },
                    "403": { "description": "Forbidden", "schema": { "type": "object" } },
                    "500": { "description": "Server error", "schema": { "type": "object" } }
                }
            }
        },
        "/api/v1/agents/ws": {
            "get": {
                "summary": "Agent WebSocket",
                "description": "WebSocket endpoint for real-time agent communication (Upgrades to WebSocket)",
                "tags": ["agents"],
                "produces": ["application/json"],
                "responses": {
                    "101": { "description": "Switching Protocols" },
                    "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } }
                }
            }
        },
        "/api/v1/agents/chat": {
            "post": {
                "summary": "Create agent chat request",
                "description": "Queue an agent chat request for processing",
                "tags": ["agents"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "body", "in": "body", "required": true, "schema": { "type": "object", "additionalProperties": true }, "description": "Agent chat request" }
                ],
                "responses": {
                    "202": { "description": "Request accepted and queued", "schema": { "type": "object", "additionalProperties": true } },
                    "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
                    "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
                }
            }
        },
        "/api/v1/agents/chat/{request_id}": {
            "get": {
                "summary": "Get agent chat status",
                "description": "Get status for a queued agent chat request",
                "tags": ["agents"],
                "produces": ["application/json"],
                "parameters": [
                    { "name": "request_id", "in": "path", "required": true, "type": "string", "description": "Request ID" }
                ],
                "responses": {
                    "200": { "description": "Status response", "schema": { "type": "object", "additionalProperties": true } },
                    "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } }
                }
            }
        },
        "/api/v1/agents/status": {
            "get": {
                "summary": "Agent system status",
                "description": "Get agent system status and queue health",
                "tags": ["agents"],
                "produces": ["application/json"],
                "responses": {
                    "200": { "description": "System status", "schema": { "type": "object", "additionalProperties": true } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } }
                }
            }
        },
        "/api/v1/agents/queues": {
            "get": {
                "summary": "Agent queues info",
                "description": "Get request/response queue details",
                "tags": ["agents"],
                "produces": ["application/json"],
                "responses": {
                    "200": { "description": "Queue information", "schema": { "type": "object", "additionalProperties": true } },
                    "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } }
                }
            }
        },
        "/api/v1/agents/": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Proxies to AI engine to list available agents and their tools",
                "produces": ["application/json"],
                "tags": ["agents"],
                "summary": "List Agents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/agents.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/agents.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/agents/{agent}/tools": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Proxies to AI engine to list tools for a given agent",
                "produces": ["application/json"],
                "tags": ["agents"],
                "summary": "List Agent Tools",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent name (e.g., product_researcher, marketer)",
                        "name": "agent",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/agents.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/agents.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/agents/{agent}/get-agent": {
            "get": {
                "description": "Proxies to AI engine to get a specific agent by identifier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Get Agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent identifier",
                        "name": "agent",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Whether the agent is for an organization",
                        "name": "is_org",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/v1/agents/{agent}/update-agent": {
            "put": {
                "description": "Proxies to AI engine to update a specific agent by identifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Update Agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent identifier",
                        "name": "agent",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Whether the agent is for an organization",
                        "name": "is_org",
                        "in": "query"
                    },
                    {
                        "description": "Agent update data",
                        "name": "updateRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AgentUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/api/v1/agents/chats": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Proxies to AI engine to list chats for the authenticated user",
                "produces": ["application/json"],
                "tags": ["agents"],
                "summary": "List Chats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/agents.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/agents.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/agents/chats/{chat_id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Proxies to AI engine to fetch a single chat by ID",
                "produces": ["application/json"],
                "tags": ["agents"],
                "summary": "Get Chat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chat ID",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/agents.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/agents.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/agents/chats/{chat_id}/messages": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Proxies to AI engine to fetch messages for a chat",
                "produces": ["application/json"],
                "tags": ["agents"],
                "summary": "Get Chat Messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chat ID",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/agents.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/agents.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/organizations": {
    "post": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Creates a new organization and assigns the creator as an admin.",
      "consumes": [
        "application/json"
      ],
      "produces": [
        "application/json"
      ],
      "tags": [
        "organizations"
      ],
      "summary": "Create an organization",
      "parameters": [
        {
          "description": "Organization data",
          "name": "organization",
          "in": "body",
          "required": true,
          "schema": {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "description": { "type": "string" },
              "employee_count": { "type": "integer", "minimum": 1 },
              "ecommerce_domain": { "type": "string" },
              "industry": { "type": "string" },
              "company_size": { "type": "string" },
              "website": { "type": "string" },
              "country": { "type": "string" },
              "city": { "type": "string" },
              "address": { "type": "string" },
              "phone_number": { "type": "string" },
              "subscription_plan": { "type": "string" }
            },
            "required": ["name", "employee_count"]
          }
        }
      ],
      "responses": {
        "201": {
          "description": "Created",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "400": {
          "description": "Bad Request",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "401": {
          "description": "Unauthorized",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "500": {
          "description": "Server Error",
          "schema": { "type": "object", "additionalProperties": true }
        }
      }
    },
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Retrieves all active organizations the authenticated user belongs to.",
      "produces": ["application/json"],
      "tags": ["organizations"],
      "summary": "List organizations",
      "responses": {
        "200": {
          "description": "OK",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "400": {
          "description": "Bad Request",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "401": {
          "description": "Unauthorized",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "500": {
          "description": "Server Error",
          "schema": { "type": "object", "additionalProperties": true }
        }
      }
    }
  },
  "/api/v1/organizations/{id}": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Retrieves details of a specific organization if the user is a member.",
      "produces": ["application/json"],
      "tags": ["organizations"],
      "summary": "Get an organization",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Organization ID",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": {
          "description": "OK",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "400": {
          "description": "Bad Request",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "401": {
          "description": "Unauthorized",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "403": {
          "description": "Forbidden",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "404": {
          "description": "Not Found",
          "schema": { "type": "object", "additionalProperties": true }
        }
      }
    },
    "put": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Updates the details of a specific organization (admin access required).",
      "consumes": ["application/json"],
      "produces": ["application/json"],
      "tags": ["organizations"],
      "summary": "Update an organization",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Organization ID",
          "required": true,
          "type": "string"
        },
        {
          "description": "Updated organization data",
          "name": "organization",
          "in": "body",
          "required": true,
          "schema": {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "description": { "type": "string" },
              "employee_count": { "type": "integer" },
              "ecommerce_domain": { "type": "string" },
              "industry": { "type": "string" },
              "company_size": { "type": "string" },
              "website": { "type": "string" },
              "country": { "type": "string" },
              "city": { "type": "string" },
              "address": { "type": "string" },
              "phone_number": { "type": "string" },
              "subscription_plan": { "type": "string" }
            }
          }
        }
      ],
      "responses": {
        "200": {
          "description": "OK",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "400": {
          "description": "Bad Request",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "401": {
          "description": "Unauthorized",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "403": {
          "description": "Forbidden",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "404": {
          "description": "Not Found",
          "schema": { "type": "object", "additionalProperties": true }
        },
        "500": {
          "description": "Server Error",
          "schema": { "type": "object", "additionalProperties": true }
        }
      }
    }
  },
"/api/v1/organizations/{id}/join": {
  "post": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Allows a user to join an organization by ID. If already a member but inactive, reactivates membership.",
    "consumes": ["application/json"],
    "produces": ["application/json"],
    "tags": ["organizations"],
    "summary": "Join an organization",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "description": "Organization ID",
        "required": true,
        "type": "string"
      },
      {
        "name": "joinData",
        "in": "body",
        "required": false,
        "schema": {
          "type": "object",
          "properties": {
            "role": { "type": "string", "default": "member" }
          }
        }
      }
    ],
    "responses": {
      "200": {
        "description": "Successfully joined organization",
        "schema": {
          "type": "object",
          "properties": {
            "message": { "type": "string" },
            "organization": {
              "type": "object",
              "properties": {
                "id": { "type": "string" },
                "name": { "type": "string" }
              }
            },
            "role": { "type": "string" }
          }
        }
      },
      "400": {
        "description": "Invalid request or ID format",
        "schema": { "type": "object", "additionalProperties": true }
      },
      "401": {
        "description": "Unauthorized",
        "schema": { "type": "object", "additionalProperties": true }
      },
      "404": {
        "description": "Organization not found",
        "schema": { "type": "object", "additionalProperties": true }
      },
      "409": {
        "description": "User is already a member",
        "schema": { "type": "object", "additionalProperties": true }
      },
      "500": {
        "description": "Server error",
        "schema": { "type": "object", "additionalProperties": true }
      }
    }
  }
},
"/api/v1/organizations/{id}/leave": {
  "post": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Allows a user to leave an organization they are currently a member of.",
    "produces": ["application/json"],
    "tags": ["organizations"],
    "summary": "Leave an organization",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "description": "Organization ID",
        "required": true,
        "type": "string"
      }
    ],
    "responses": {
      "200": {
        "description": "Successfully left organization",
        "schema": {
          "type": "object",
          "properties": {
            "message": { "type": "string" }
          }
        }
      },
      "400": {
        "description": "Invalid request or ID format",
        "schema": { "type": "object", "additionalProperties": true }
      },
      "401": {
        "description": "Unauthorized",
        "schema": { "type": "object", "additionalProperties": true }
      },
      "404": {
        "description": "User is not a member",
        "schema": { "type": "object", "additionalProperties": true }
      },
      "500": {
        "description": "Server error",
        "schema": { "type": "object", "additionalProperties": true }
      }
    }
  }
},
"/api/v1/organizations/{id}/members": {
  "get": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Retrieves all active members of the specified organization. Requires the requester to be a current member.",
    "produces": ["application/json"],
    "tags": ["members"],
    "summary": "List members of an organization",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "description": "Organization ID",
        "required": true,
        "type": "string"
      }
    ],
    "responses": {
      "200": {
        "description": "List of members",
        "schema": {
          "type": "object",
          "properties": {
            "members": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": { "type": "string" },
                  "email": { "type": "string" },
                  "name": { "type": "string" },
                  "role": { "type": "string" },
                  "joined_at": { "type": "string", "format": "date-time" },
                  "is_active": { "type": "boolean" }
                }
              }
            }
          }
        }
      },
      "400": { "description": "Invalid ID format", "schema": { "type": "object", "additionalProperties": true } },
      "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
      "403": { "description": "Not a member of organization", "schema": { "type": "object", "additionalProperties": true } },
      "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
    }
  },
  "post": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Allows an admin to add a member to the organization by email. If membership existed but inactive, reactivates it.",
    "consumes": ["application/json"],
    "produces": ["application/json"],
    "tags": ["members"],
    "summary": "Add member to organization",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "description": "Organization ID",
        "required": true,
        "type": "string"
      },
      {
        "name": "memberData",
        "in": "body",
        "required": true,
        "schema": {
          "type": "object",
          "properties": {
            "email": { "type": "string" },
            "role": { "type": "string", "enum": ["admin", "member", "viewer"], "default": "member" }
          }
        }
      }
    ],
    "responses": {
      "201": {
        "description": "Member successfully added",
        "schema": {
          "type": "object",
          "properties": {
            "message": { "type": "string" },
            "member": {
              "type": "object",
              "properties": {
                "id": { "type": "string" },
                "email": { "type": "string" },
                "role": { "type": "string" }
              }
            }
          }
        }
      },
      "400": { "description": "Invalid request body or ID format", "schema": { "type": "object", "additionalProperties": true } },
      "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
      "403": { "description": "Only admins can add members", "schema": { "type": "object", "additionalProperties": true } },
      "404": { "description": "User or organization not found", "schema": { "type": "object", "additionalProperties": true } },
      "409": { "description": "User already active member", "schema": { "type": "object", "additionalProperties": true } },
      "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
    }
  }
},
"/api/v1/organizations/{id}/members/{memberId}": {
  "delete": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Allows an admin to remove a member from the organization. Uses soft deletion (deactivation). Prevents removing yourself if last admin.",
    "produces": ["application/json"],
    "tags": ["members"],
    "summary": "Remove member from organization",
    "parameters": [
      { "name": "id", "in": "path", "description": "Organization ID", "required": true, "type": "string" },
      { "name": "memberId", "in": "path", "description": "Member ID", "required": true, "type": "string" }
    ],
    "responses": {
      "200": { "description": "Member successfully removed", "schema": { "type": "object", "properties": { "message": { "type": "string" } } } },
      "400": { "description": "Invalid ID format or attempt to remove last admin", "schema": { "type": "object", "additionalProperties": true } },
      "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
      "403": { "description": "Only admins can remove members", "schema": { "type": "object", "additionalProperties": true } },
      "404": { "description": "Member not found", "schema": { "type": "object", "additionalProperties": true } },
      "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
    }
  },
  "put": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Allows an admin to update a member's role within the organization. Prevents self-demotion if last admin.",
    "consumes": ["application/json"],
    "produces": ["application/json"],
    "tags": ["members"],
    "summary": "Update member role",
    "parameters": [
      { "name": "id", "in": "path", "description": "Organization ID", "required": true, "type": "string" },
      { "name": "memberId", "in": "path", "description": "Member ID", "required": true, "type": "string" },
      {
        "name": "roleData",
        "in": "body",
        "required": true,
        "schema": {
          "type": "object",
          "properties": {
            "role": { "type": "string", "enum": ["admin", "member", "viewer"] }
          }
        }
      }
    ],
    "responses": {
      "200": {
        "description": "Member role updated",
        "schema": {
          "type": "object",
          "properties": {
            "message": { "type": "string" },
            "member": {
              "type": "object",
              "properties": {
                "id": { "type": "string" },
                "role": { "type": "string" }
              }
            }
          }
        }
      },
      "400": { "description": "Invalid request body or ID format", "schema": { "type": "object", "additionalProperties": true } },
      "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
      "403": { "description": "Only admins can update member roles", "schema": { "type": "object", "additionalProperties": true } },
      "404": { "description": "Member not found", "schema": { "type": "object", "additionalProperties": true } },
      "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
    }
  }
},
"/api/v1/organizations/{id}/business-profile": {
  "post": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Creates a new organization business profile if it doesn’t exist, otherwise updates the existing profile. Only organization admins can perform this action.",
    "consumes": ["application/json"],
    "produces": ["application/json"],
    "tags": ["organization-business-profile"],
    "summary": "Create or update organization business profile",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "description": "Organization ID",
        "required": true,
        "type": "string"
      },
      {
        "name": "profile",
        "in": "body",
        "required": true,
        "schema": {
          "type": "object",
          "properties": {
            "business_hours": { "type": "string" },
            "primary_markets": { "type": "array", "items": { "type": "string" } },
            "default_currency": { "type": "string" },
            "supported_languages": { "type": "array", "items": { "type": "string" } },
            "support_email": { "type": "string" },
            "support_channels": { "type": "array", "items": { "type": "string" } },
            "social_links": { "type": "object", "additionalProperties": { "type": "string" } },
            "fulfillment_method": { "type": "string" },
            "shipping_carriers": { "type": "array", "items": { "type": "string" } },
            "returns_policy_url": { "type": "string" },
            "payment_gateways": { "type": "array", "items": { "type": "string" } },
            "tax_identifiers": { "type": "object", "additionalProperties": { "type": "string" } },
            "primary_contacts": { "type": "array", "items": { "type": "object" } },
            "compliance_contacts": { "type": "array", "items": { "type": "object" } },
            "ecommerce_platforms": { "type": "array", "items": { "type": "object" } },
            "key_systems": { "type": "array", "items": { "type": "string" } },
            "holiday_blackout_dates": { "type": "array", "items": { "type": "string" } },
            "data_processing_addenda": { "type": "string" }
          }
        }
      }
    ],
    "responses": {
      "200": {
        "description": "Business profile created or updated successfully",
        "schema": { "$ref": "#/definitions/OrganizationBusinessProfileResponse" }
      },
      "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
      "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
      "403": { "description": "Forbidden – Only admin can modify business profile", "schema": { "type": "object", "additionalProperties": true } },
      "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
    }
  },
  "get": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Retrieves the business profile of an organization. Only organization admins can view it.",
    "produces": ["application/json"],
    "tags": ["organization-business-profile"],
    "summary": "Get organization business profile",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "description": "Organization ID",
        "required": true,
        "type": "string"
      }
    ],
    "responses": {
      "200": {
        "description": "Organization business profile retrieved successfully",
        "schema": { "$ref": "#/definitions/OrganizationBusinessProfileResponse" }
      },
      "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
      "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
      "403": { "description": "Forbidden – Only admin can view business profile", "schema": { "type": "object", "additionalProperties": true } },
      "404": { "description": "Business profile not found", "schema": { "type": "object", "additionalProperties": true } }
    }
  },
  "delete": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Deletes an organization's business profile. Only organization admins can perform this action.",
    "tags": ["organization-business-profile"],
    "summary": "Delete organization business profile",
    "parameters": [
      {
        "name": "id",
        "in": "path",
        "description": "Organization ID",
        "required": true,
        "type": "string"
      }
    ],
    "responses": {
      "200": {
        "description": "Organization business profile deleted successfully",
        "schema": {
          "type": "object",
          "properties": {
            "message": { "type": "string" }
          }
        }
      },
      "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
      "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
      "403": { "description": "Forbidden – Only admin can delete business profile", "schema": { "type": "object", "additionalProperties": true } },
      "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
    }
  }
},

  "/api/v1/assets/categories": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Retrieves a list of all supported asset categories with ID, name, and description.",
      "produces": ["application/json"],
      "tags": ["assets"],
      "summary": "List asset categories",
      "responses": {
        "200": {
          "description": "List of categories",
          "schema": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": { "type": "string" },
                "name": { "type": "string" },
                "description": { "type": "string" }
              }
            }
          }
        },
        "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },

  "/api/v1/assets/{id}": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Retrieves detailed information about a specific asset, including secure URL if stored in Cloudinary.",
      "produces": ["application/json"],
      "tags": ["assets"],
      "summary": "Get asset details",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Asset ID (UUID)",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "Asset details", "schema": { "$ref": "#/definitions/AssetResponse" } },
        "400": { "description": "Invalid asset ID", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "403": { "description": "Forbidden", "schema": { "type": "object", "additionalProperties": true } },
        "404": { "description": "Asset not found", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
      }
    },
    "delete": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Deletes an asset record and removes its file from Cloudinary if applicable. Only organization admins can delete organization assets.",
      "produces": ["application/json"],
      "tags": ["assets"],
      "summary": "Delete an asset",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Asset ID (UUID)",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "Asset deleted successfully", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Invalid asset ID", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "403": { "description": "Forbidden", "schema": { "type": "object", "additionalProperties": true } },
        "404": { "description": "Asset not found", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },
  "/api/v1/assets": {
  "get": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Lists all assets belonging to a user or organization, with optional category filter.",
    "produces": ["application/json"],
    "tags": ["assets"],
    "summary": "List assets",
    "parameters": [
      {
        "name": "organization_id",
        "in": "query",
        "description": "Organization ID (UUID)",
        "required": false,
        "type": "string"
      },
      {
        "name": "category",
        "in": "query",
        "description": "Asset category filter (business_profile, brand_assets, marketing_assets, analytics_reports, policy_documents, media_documents)",
        "required": false,
        "type": "string"
      }
    ],
    "responses": {
      "200": { "description": "List of assets", "schema": { "type": "array", "items": { "$ref": "#/definitions/AssetResponse" } } },
      "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
      "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
      "403": { "description": "Forbidden", "schema": { "type": "object", "additionalProperties": true } },
      "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
    }
  },
  "post": {
    "security": [
      {
        "BearerAuth": []
      }
    ],
    "description": "Uploads a new asset to Cloudinary and stores metadata in the database.",
    "consumes": ["multipart/form-data"],
    "produces": ["application/json"],
    "tags": ["assets"],
    "summary": "Upload asset",
    "parameters": [
      {
        "name": "organization_id",
        "in": "formData",
        "description": "Organization ID (UUID)",
        "required": true,
        "type": "string"
      },
      {
        "name": "category",
        "in": "formData",
        "description": "Category of the asset (business_profile, brand_assets, marketing_assets, analytics_reports, policy_documents, media_documents)",
        "required": true,
        "type": "string"
      },
      {
        "name": "file",
        "in": "formData",
        "description": "The file to upload",
        "required": true,
        "type": "file"
      }
    ],
    "responses": {
      "201": { "description": "Asset successfully uploaded", "schema": { "$ref": "#/definitions/AssetResponse" } },
      "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
      "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
      "403": { "description": "Forbidden", "schema": { "type": "object", "additionalProperties": true } },
      "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
    }
  }
},
  "/organizations/{id}/invite": {
    "post": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Sends an invitation to a user via email to join an organization with a specified role. Only organization admins can send invitations.",
      "consumes": ["application/json"],
      "produces": ["application/json"],
      "tags": ["invitations"],
      "summary": "Invite member to organization",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Organization ID (UUID)",
          "required": true,
          "type": "string"
        },
        {
          "name": "body",
          "in": "body",
          "description": "Invitation request payload",
          "required": true,
          "schema": {
            "type": "object",
            "properties": {
              "email": { "type": "string", "format": "email" },
              "role": { "type": "string", "enum": ["admin", "member", "viewer"] }
            }
          }
        }
      ],
      "responses": {
        "201": { "description": "Invitation sent successfully" },
        "400": { "description": "Invalid request or ID format" },
        "401": { "description": "Unauthorized" },
        "403": { "description": "Forbidden – only admins can invite members" },
        "404": { "description": "Organization not found" },
        "409": { "description": "Conflict – user already a member or pending invitation exists" },
        "500": { "description": "Server error" }
      }
    }
  },

  "/invitations/{id}/accept": {
    "post": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Allows a user to accept a pending organization invitation sent to their email.",
      "produces": ["application/json"],
      "tags": ["invitations"],
      "summary": "Accept invitation",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Invitation ID (UUID)",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "Successfully joined organization" },
        "400": { "description": "Invalid request or invitation expired" },
        "401": { "description": "Unauthorized" },
        "403": { "description": "Forbidden – email mismatch" },
        "404": { "description": "Invitation not found or already processed" },
        "409": { "description": "Conflict – user already a member" },
        "500": { "description": "Server error" }
      }
    }
  },

  "/organizations/{id}/invitations": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Retrieves all invitations (pending, expired, accepted) for a given organization. Only admins can view.",
      "produces": ["application/json"],
      "tags": ["invitations"],
      "summary": "List organization invitations",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Organization ID (UUID)",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": {
          "description": "List of invitations",
          "schema": {
            "type": "array",
            "items": { "$ref": "#/definitions/InvitationResponse" }
          }
        },
        "400": { "description": "Invalid request or ID format" },
        "401": { "description": "Unauthorized" },
        "403": { "description": "Forbidden – only admins can view invitations" },
        "500": { "description": "Server error" }
      }
    }
  },

  "/organizations/{id}/invitations/{invitationId}": {
    "delete": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Allows an admin to cancel a pending organization invitation. Only pending invitations can be canceled.",
      "produces": ["application/json"],
      "tags": ["invitations"],
      "summary": "Cancel invitation",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Organization ID (UUID)",
          "required": true,
          "type": "string"
        },
        {
          "name": "invitationId",
          "in": "path",
          "description": "Invitation ID (UUID)",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "Invitation cancelled successfully" },
        "400": { "description": "Invalid request or invitation not pending" },
        "401": { "description": "Unauthorized" },
        "403": { "description": "Forbidden – only admins can cancel invitations" },
        "404": { "description": "Invitation not found" },
        "500": { "description": "Server error" }
      }
    }
  },

  "/organizations/{id}/invitations/{invitationId}/resend": {
    "post": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Allows an admin to resend an expired invitation, extending its expiration by 7 days.",
      "produces": ["application/json"],
      "tags": ["invitations"],
      "summary": "Resend invitation",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Organization ID (UUID)",
          "required": true,
          "type": "string"
        },
        {
          "name": "invitationId",
          "in": "path",
          "description": "Invitation ID (UUID)",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "Invitation resent successfully" },
        "400": { "description": "Invalid request or invitation not expired" },
        "401": { "description": "Unauthorized" },
        "403": { "description": "Forbidden – only admins can resend invitations" },
        "404": { "description": "Invitation not found" },
        "500": { "description": "Server error" }
      }
    }
  },

  "/api/v1/todos": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Retrieves all todos belonging to the authenticated user, optionally filtered by status or priority",
      "produces": ["application/json"],
      "tags": ["todos"],
      "summary": "List all todos for the authenticated user",
      "parameters": [
        {
          "name": "status",
          "in": "query",
          "description": "Filter by status (todo, in_progress, done)",
          "required": false,
          "type": "string"
        },
        {
          "name": "priority",
          "in": "query",
          "description": "Filter by priority (high, medium, low)",
          "required": false,
          "type": "string"
        },
        {
          "name": "organization_id",
          "in": "query",
          "description": "Filter by organization ID",
          "required": false,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "List of todos", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
      }
    },
    "post": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Creates a new todo item for the authenticated user",
      "consumes": ["application/json"],
      "produces": ["application/json"],
      "tags": ["todos"],
      "summary": "Create a new todo",
      "parameters": [
        {
          "name": "body",
          "in": "body",
          "description": "Todo data",
          "required": true,
          "schema": { "type": "object", "additionalProperties": true }
        }
      ],
      "responses": {
        "201": { "description": "Created todo", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },

  "/api/v1/todos/{id}": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Retrieves a single todo by its ID",
      "produces": ["application/json"],
      "tags": ["todos"],
      "summary": "Get a specific todo by ID",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Todo ID",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "Todo details", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "404": { "description": "Todo not found", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
      }
    },
    "put": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Updates an existing todo item",
      "consumes": ["application/json"],
      "produces": ["application/json"],
      "tags": ["todos"],
      "summary": "Update a todo",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Todo ID",
          "required": true,
          "type": "string"
        },
        {
          "name": "body",
          "in": "body",
          "description": "Updated todo data",
          "required": true,
          "schema": { "type": "object", "additionalProperties": true }
        }
      ],
      "responses": {
        "200": { "description": "Updated todo", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "404": { "description": "Todo not found", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
      }
    },
    "delete": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Deletes a todo item (soft delete)",
      "produces": ["application/json"],
      "tags": ["todos"],
      "summary": "Delete a todo",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Todo ID",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "Success message", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "404": { "description": "Todo not found", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },

  "/api/v1/todos/{id}/complete": {
    "patch": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Marks a todo as completed (status = done, progress = 100)",
      "produces": ["application/json"],
      "tags": ["todos"],
      "summary": "Mark a todo as done",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Todo ID",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "Updated todo", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "404": { "description": "Todo not found", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },

  "/api/v1/todos/{id}/schedule-agent": {
    "post": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Associates an agent task with a todo and schedules it",
      "consumes": ["application/json"],
      "produces": ["application/json"],
      "tags": ["todos"],
      "summary": "Schedule an agent task for a todo",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Todo ID",
          "required": true,
          "type": "string"
        },
        {
          "name": "body",
          "in": "body",
          "description": "Agent task configuration",
          "required": true,
          "schema": { "type": "object", "additionalProperties": true }
        }
      ],
      "responses": {
        "200": { "description": "Updated todo with agent task", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "404": { "description": "Todo not found", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Server error", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },

  "/api/v1/todos/status/{status}": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Retrieves all todos filtered by status",
      "produces": ["application/json"],
      "tags": ["todos"],
      "summary": "Get todos by status",
      "parameters": [
        {
          "name": "status",
          "in": "path",
          "description": "Status (todo, in_progress, done)",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "List of todos", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Invalid status", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },

  "/api/v1/todos/priority/{priority}": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Retrieves all todos filtered by priority",
      "produces": ["application/json"],
      "tags": ["todos"],
      "summary": "Get todos by priority",
      "parameters": [
        {
          "name": "priority",
          "in": "path",
          "description": "Priority (high, medium, low)",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "List of todos", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Invalid priority", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },

  "/api/v1/workflow-template/n8n/import": {
    "post": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Import an N8N workflow template from JSON",
      "consumes": ["application/json"],
      "produces": ["application/json"],
      "tags": ["workflow"],
      "summary": "Import workflow from JSON",
      "parameters": [
        {
          "name": "body",
          "in": "body",
          "description": "Workflow import data",
          "required": true,
          "schema": { "type": "object", "additionalProperties": true }
        }
      ],
      "responses": {
        "200": { "description": "Workflow imported successfully", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },

  "/api/v1/workflow-template/n8n/": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Retrieve a list of workflow templates",
      "produces": ["application/json"],
      "tags": ["workflow"],
      "summary": "Get workflow templates",
      "parameters": [
        {
          "name": "limit",
          "in": "query",
          "description": "Limit",
          "required": false,
          "type": "integer",
          "default": 10
        },
        {
          "name": "n8n_json",
          "in": "query",
          "description": "Include n8n_json",
          "required": false,
          "type": "boolean",
          "default": true
        }
      ],
      "responses": {
        "200": { "description": "List of workflow templates", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },

  "/api/v1/workflow-template/n8n/{id}": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Retrieve a specific N8N workflow template by its ID",
      "produces": ["application/json"],
      "tags": ["workflow"],
      "summary": "Get workflow template",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Workflow Template ID",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "Workflow template details", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "404": { "description": "Workflow template not found", "schema": { "type": "object", "additionalProperties": true } }
      }
    },
    "delete": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Delete a specific N8N workflow template by its ID",
      "produces": ["application/json"],
      "tags": ["workflow"],
      "summary": "Delete workflow template",
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Workflow Template ID",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "Workflow template deleted successfully", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Invalid request", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "404": { "description": "Workflow template not found", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },
  "/api/v1/analytics/agent/runs": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Proxies to AI engine analytics agent runs endpoint.",
      "produces": ["application/json"],
      "tags": ["analytics"],
      "summary": "List agent runs (paginated)",
      "parameters": [
        {
          "name": "agent_identifier",
          "in": "query",
          "description": "Filter by agent identifier",
          "required": false,
          "type": "string"
        },
        {
          "name": "start_date",
          "in": "query",
          "description": "Inclusive start datetime (RFC3339)",
          "required": false,
          "type": "string"
        },
        {
          "name": "end_date",
          "in": "query",
          "description": "Inclusive end datetime (RFC3339)",
          "required": false,
          "type": "string"
        },
        {
          "name": "org_only",
          "in": "query",
          "description": "If true, only org runs are allowed",
          "required": false,
          "type": "boolean"
        },
        {
          "name": "page",
          "in": "query",
          "description": "Page number (min 1)",
          "required": false,
          "type": "integer"
        },
        {
          "name": "page_size",
          "in": "query",
          "description": "Page size (min 1, max 100)",
          "required": false,
          "type": "integer"
        }
      ],
      "responses": {
        "200": { "description": "OK", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Bad Request", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Internal Server Error", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },
  "/api/v1/analytics/agent/usage": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Proxies to AI engine analytics agent usage endpoint.",
      "produces": ["application/json"],
      "tags": ["analytics"],
      "summary": "Get aggregated agent usage",
      "parameters": [
        {
          "name": "agent_identifiers",
          "in": "query",
          "description": "Filter by agent identifiers",
          "required": false,
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        {
          "name": "org_only",
          "in": "query",
          "description": "If true, only org runs are allowed",
          "required": false,
          "type": "boolean"
        },
        {
          "name": "start_date",
          "in": "query",
          "description": "Inclusive start datetime (RFC3339)",
          "required": false,
          "type": "string"
        },
        {
          "name": "end_date",
          "in": "query",
          "description": "Inclusive end datetime (RFC3339)",
          "required": false,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "OK", "schema": { "type": "array", "items": { "type": "object", "additionalProperties": true } } },
        "400": { "description": "Bad Request", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Internal Server Error", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },
  "/api/v1/analytics/tool/executions": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Proxies to AI engine analytics tool executions endpoint.",
      "produces": ["application/json"],
      "tags": ["analytics"],
      "summary": "List tool runs (paginated)",
      "parameters": [
        {
          "name": "tool_name",
          "in": "query",
          "description": "Filter by tool name",
          "required": false,
          "type": "string"
        },
        {
          "name": "status",
          "in": "query",
          "description": "Filter by status: running|succeeded|failed",
          "required": false,
          "type": "string"
        },
        {
          "name": "ignitic_identifier",
          "in": "query",
          "description": "Filter by ignitic identifier",
          "required": false,
          "type": "string"
        },
        {
          "name": "chat_id",
          "in": "query",
          "description": "Filter by chat id",
          "required": false,
          "type": "string"
        },
        {
          "name": "is_workflow",
          "in": "query",
          "description": "Filter by workflow executions",
          "required": false,
          "type": "boolean"
        },
        {
          "name": "workflow_provider",
          "in": "query",
          "description": "Filter by workflow provider",
          "required": false,
          "type": "string"
        },
        {
          "name": "start_date",
          "in": "query",
          "description": "Inclusive start datetime (RFC3339)",
          "required": false,
          "type": "string"
        },
        {
          "name": "end_date",
          "in": "query",
          "description": "Inclusive end datetime (RFC3339)",
          "required": false,
          "type": "string"
        },
        {
          "name": "org_only",
          "in": "query",
          "description": "If true, only org executions are allowed",
          "required": false,
          "type": "boolean"
        },
        {
          "name": "page",
          "in": "query",
          "description": "Page number (default 1, min 1)",
          "required": false,
          "type": "integer"
        },
        {
          "name": "page_size",
          "in": "query",
          "description": "Page size (default 50, min 1, max 100)",
          "required": false,
          "type": "integer"
        }
      ],
      "responses": {
        "200": { "description": "OK", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Bad Request", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Internal Server Error", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  },
  "/api/v1/analytics/tool/executions/{execution_id}": {
    "get": {
      "security": [
        {
          "BearerAuth": []
        }
      ],
      "description": "Proxies to AI engine analytics tool execution-by-id endpoint.",
      "produces": ["application/json"],
      "tags": ["analytics"],
      "summary": "Get single tool run",
      "parameters": [
        {
          "name": "execution_id",
          "in": "path",
          "description": "Tool execution id (Mongo ObjectId)",
          "required": true,
          "type": "string"
        }
      ],
      "responses": {
        "200": { "description": "OK", "schema": { "type": "object", "additionalProperties": true } },
        "400": { "description": "Bad Request", "schema": { "type": "object", "additionalProperties": true } },
        "401": { "description": "Unauthorized", "schema": { "type": "object", "additionalProperties": true } },
        "500": { "description": "Internal Server Error", "schema": { "type": "object", "additionalProperties": true } }
      }
    }
  }







    },
    "definitions": {
        "AgentUpdateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "system_prompt": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "IgniticAI API",
	Description:      "API documentation for IgniticAI backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
